### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by hollanderbart** [flockoffiles/SwiftySRP#5]
For my current project, I don't use Cocoapods but use Carthage as the dependency manager. Is it possible to support it via a shared framework?

```Dependency "SwiftySRP" has no shared framework schemes for any of the platforms: iOS```

**Comment by flockoffiles** [comment]
We also use Carthage with SwiftySRP and have no problems.
The scheme SwiftySRP-iOS IS shared.

Maybe, you are using an outdated version?

**Comment by hollanderbart** [comment]
It appeared there was a cached version that was broken. Removing the cached version resolved it. Thanks for your support. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
